name: Python CI

on:
  push:
    branches: [ main ] # Se ejecuta cuando hay un push en la rama "main"
  pull_request:
    branches: [ main ] # Se ejecuta cuando se abre un pull request hacia la rama "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Run tests
      run: | # El uso del carácter | permite escribir múltiples líneas de comandos en el bloque run. Cada comando se ejecutará en una línea separada.
        python -m unittest test_suma.py
        python -m unittest test_resta.py
        python -m unittest test_multiplicacion.py
        python -m unittest test_division.py
